version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hosting-center-web
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./vendor:/var/www/vendor
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./clients:/var/www/clients    # локальная папка для клиентских данных
      - /var/run/docker.sock:/var/run/docker.sock
      - ./domains:/domains 
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  ftp:
    build:
      context: .
      dockerfile: Dockerfile.ftp
    container_name: hosting-center-ftp
    restart: "no"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftpdata:/home/ftpuser
      - ./clients:/var/www/clients
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: hosting-center-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mojafirma
      MYSQL_USER: mojafirma_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  smtp:
    image: mailhog/mailhog
    container_name: hosting-center-smtp
    ports:
      - "1025:1025"   # SMTP порт
      - "8025:8025"   # веб-интерфейс MailHog

volumes:
  db_data:
